language: node_js
node_js:
  - 10.16.3
cache: npm

# before_install:
install:
  - npm ci

script:
  - npm test
  - npm run build
# before_script:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy: