language: node_js
node_js:
  - 10.16.3
cache: npm

# before_install:
install:
  - npm ci

script:
  - npm test
  - npm run build
# before_script:
# after_success:
# after_failure:
# before_deploy:
# deploy:
#   provider: netlify
#   site: a1b775e9-1571-4737-8c4a-5ce45b35ffe7
# after_deploy: